spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop


api:
  v1:
    prefix: api/v1
